//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetingApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SavingsGoal
    {
        public int SavingGoalID { get; set; }
        public int ClientID { get; set; }
        public string GoalDescription { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int SavingsPointValue { get; set; }
        public decimal SavingsGoalAmount { get; set; }
        public decimal CurrentGoalAmount { get; set; }
        public string Recurring { get; set; }
        public string Status { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
